---
repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        files: \.(yaml|yml)$
        args:
          - -conf
          - yamlfmt.yml
          - -gitignore_excludes
          - -v
  - repo: local
    hooks:
      - id: sops-auto-encrypt
        name: SOPS Auto-Encrypt
        entry: bash ./encrypt-sops.sh
        language: system
        files: '(\.secrets\.ya?ml$)'
  - repo: local
    hooks:
      - id: whitelist-sort-unique
        name: Whitelist Sort and Unique
        entry: bash -c 'sort -u -o beets/whitelist.txt beets/whitelist.txt'
        language: system
        files: beets/whitelist\.txt
        pass_filenames: false
