---
services:
  tidal-dl-ng:
    build: .
    container_name: tidal-dl-ng
    volumes:
      - /opt/tidal-dl-ng/config:/config
      - ${MEDIA}/musics/not_imported:/downloads
    restart: unless-stopped
