---
services:
  tidal-dl-ng:
    build: .
    container_name: tidal-dl-ng
    user: "1000:1000"
    volumes:
      - /opt/tidal-dl-ng/config:/config
      - ${MEDIA}/downloads/tidal:/downloads
      - ./scripts/download-loop.sh:/app/download-loop.sh:ro
    restart: unless-stopped
    command: /app/download-loop.sh
