---
services:
  komga:
    image: gotson/komga
    container_name: komga
    env_file:
      - .env
    networks:
      proxy:
    volumes:
      - /opt/komga/config:/config
      - ${MEDIA}/books:/data
    user: "1000:1000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.komga-secure.entrypoints=https"
      - "traefik.http.routers.komga-secure.rule=Host(`komga.${DOMAIN}`)"
      - "traefik.http.routers.komga-secure.tls=true"
      - "traefik.http.routers.komga-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.komga-secure.service=komga"
      - "traefik.http.routers.komga-secure.middlewares=compress@file"
      - "traefik.http.services.komga.loadbalancer.server.port=25600"
networks:
  proxy:
    external: true
