---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      proxy:
      vpn:
        ipv4_address: 172.32.0.16
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: ${TIMEZONE}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - /opt/pihole/etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pihole-secure.entrypoints=https"
      - "traefik.http.routers.pihole-secure.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.routers.pihole-secure.tls=true"
      - "traefik.http.routers.pihole-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.pihole-secure.service=pihole"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - diun.enable=true
    command: >-
      /bin/sh -c " VPN_IF=$(ifconfig | grep -B1 172.32.0.16 | grep -o '^\w*'); ip rule add from all table 200 pref 100; ip route add default via 172.32.0.4 dev $VPN_IF table 200 || true; ip route add 172.32.0.0/16 via 172.32.0.1 dev $VPN_IF table 200 || true; iptables -t nat -A POSTROUTING -o $VPN_IF -j MASQUERADE; s6-svscan /etc/s6 "
networks:
  proxy:
    external: true
  vpn:
    external: true
