---
services:
  qbit_manage:
    extends:
      file: ../common.yml
      service: common-config
    image: ghcr.io/stuffanthings/qbit_manage:latest
    container_name: qbit_manage
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - /opt/qbit_manage/config:/config:rw
      - ${MEDIA}/downloads:/data/torrents:rw
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.qbit_manage-secure.entrypoints=https
      - traefik.http.routers.qbit_manage-secure.rule=Host(`qbit_manage.${DOMAIN}`)
      - traefik.http.routers.qbit_manage-secure.tls=true
      - traefik.http.routers.qbit_manage-secure.tls.certresolver=cloudflare
      - traefik.http.routers.qbit_manage-secure.service=qbit_manage
      - traefik.http.services.qbit_manage.loadbalancer.server.port=8080
