---
plugins:
  - info
  - duplicates
  - permissions
  - mbsync
  - missing
  - musicbrainz
  - web
  - scrub
  - inline
  - hook
directory: /music
library: /config/musiclibrary.blb
timeout: 60.0
threaded: yes
original_date: no
per_disc_numbering: no
paths:
  'disctotal:1': '${albumartist}/${album}/${albumartist}_${album}_${track}_$safe_title'
  default: '${albumartist}/${album}/${albumartist}_${album}_${disc}-${track}_$safe_title'
item_fields:
  safe_title: |
    import re
    return title.replace('/', '∕')
asciify_paths: no
import:
  write: yes
  copy: no
  move: yes
  resume: ask
  incremental: yes
  quiet_fallback: skip
  timid: no
  log: /config/beet.log
scrub:
  auto: yes
match:
  strong_rec_thresh: 0.15
  preferred:
    media: ['Digital Media']
  ignored_media:
    - 'None'
    - 'Other'
    - ''
    - 'CD'
    - 'Vinyl'
    - '12" Vinyl'
    - '7" Vinyl'
    - '10" Vinyl'
    - 'Cassette'
    - 'SACD'
    - 'DualDisc'
    - 'DVD-Audio'
    - 'Blu-ray'
    - 'Data CD'
    - 'CD-R'
    - '8-Track'
    - 'DCC'
    - 'MiniDisc'
web:
  host: 0.0.0.0
  port: 8337
permissions:
  file: 644
  dir: 755
duplicates:
  full: yes
  format: '$albumartist - $title : $path'
  checksum: ffmpeg -i {file} -f crc -
hook:
  hooks:
    - event: album_imported
      format: "Hook lancé pour: {album.path}"
      command: /config/beets-process-queue.sh "{album.path}"
