---
services:
  beets:
    build: .
    container_name: beets
    networks:
      proxy:
    env_file:
      - .env
    volumes:
      - /opt/beets/config:/config
      - ./config.yaml:/config/config.yaml
      - ./heavy.yaml:/config/heavy.yaml
      - ${MEDIA}/musics:/music
      - ${MEDIA}/downloads/deemix:/downloads
      - /usr/local/bin/beets-discord-notify.sh:/scripts/beets-discord-notify.sh:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.beets-secure.entrypoints=https"
      - "traefik.http.routers.beets-secure.rule=Host(`beets.${DOMAIN}`)"
      - "traefik.http.routers.beets-secure.tls=true"
      - "traefik.http.routers.beets-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.beets-secure.service=beets"
      - "traefik.http.routers.beets-secure.middlewares=compress@file"
      - "traefik.http.services.beets.loadbalancer.server.port=8337"
networks:
  proxy:
    external: true
