---
services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/webhook:2.8.1
    container_name: webhook
    ports:
      - "9000:9000"
    volumes:
      - ./hooks:/etc/webhook
      - ./scripts:/opt/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    command: -verbose -hooks=/etc/webhook/hooks.json -hotreload
    restart: unless-stopped
