---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:nightly
    container_name: radarr
    env_file:
      - .env
    networks:
      proxy:
    mem_limit: 1024M
    volumes:
      - /opt/radarr/config:/config
      - /opt/radarr/custom-services.d:/custom-services.d
      - ./custom-cont-init.d:/custom-cont-init.d
      - ${MEDIA}:/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.${DOMAIN}`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.routers.radarr-secure.middlewares=compress@file"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
networks:
  proxy:
    external: true
