---
general:
  checkNewVersion: false
  sendAnonymousUsage: false
ping:
  entryPoint: traefik
api:
  dashboard: true
  debug: false
  insecure: false
log:
  level: INFO
accessLog: {}
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
  traefik:
    address: :8080
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/config.yml
certificatesResolvers:
  cloudflare:
    acme:
      # caServer: https://acme-v02.api.letsencrypt.org/directory # production (default)
      # staging (testing)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: ENC[AES256_GCM,data:NkleY7scorFWJ2wKp3MjfK00BhiB5g==,iv:tzOSG2nyfeZojel5SZZh6DdfidaEEtT1MCDhINQmWHM=,tag:1WrcNCyW+quPJrm6oRplgw==,type:str]
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # disablePropagationCheck: true # Some people using Cloudflare note this can solve DNS propagation issues.

        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
sops:
  age:
    - recipient: age10tes8xka8mh6u72vvunf7umwfqv2qquswzwmr6wrcy3yffvut9rqdtthsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN3lBR3B4U2FIRHV0VGpq
        NmtnWW83cytkUEJ5Zjg3aVdHSzQrNXlFUUM4CkQ2cmpDMnFnVmtxTFZONXplU1JI
        MSt2OGlPZlBHdmdvWkxtSzJNQ0FjUGcKLS0tIE5TbnRkcVIzemg1azVNUllqNjVt
        bUI1RmtOczJnQ3V5V1ZKK3VvVlJrQjgKjqUNXWocIr0A4me0rh6saajeFCmxHigT
        u/oLBe3jko3GwoE5j1TZZ7rCETfqzM2UVIrxpO+1flbVcbP/p8Jrdg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kgzzjlugy0smkex77kvymuwjlhfryh0ljnmqqaw8zx9hh3st0vysha3g97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOU5yU1RFMGJ1MG5RWTBH
        eXlWYlFRQVBYNFZDOG1sVTFXNHAxWk9PM0ZRCkZ1YWRXL2hCeEtnb0VVZUloaGdz
        VVRwblYyUExkTXRSTklrR2wyYmRwSFUKLS0tIHlqVU52TlV1UG5vYzhyQ1E4NFpr
        UjV1ZWgrbG9TdzZBQktPSTBrVnRkN3MKEbpCinlRdhzXtczrTNMgI9KcjPVRF6yv
        v2INRLHk6NQlOOafP+p6lGDI8h84Olm69+Qp1a8cEHOAfCo0XnPZnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T11:32:23Z"
  mac: ENC[AES256_GCM,data:ft9K1q8prjASayZzKF6992M46QIc+MpLE3qcssoK7nzqADbYS7elkXkE6e/6cuSNYoHlLYxBoySLQo6/Xhem4iBO/lNk/+lvig/jNS5keFnP+lAm6tME6x9hg+y4wSsHeuAC89oVjaPO4SnENVsMtghvK8gXqe5TMhqzTvAfV4U=,iv:kEHDYrEr/OURPsFILk3pQH+KpFTR1WgjZANHOMbT/XI=,tag:fpARpXNHwKfBWcfaR/ZNvA==,type:str]
  encrypted_regex: ^(webhookURL|email)$
  version: 3.11.0
