---
general:
  checkNewVersion: false
  sendAnonymousUsage: true
ping:
  entryPoint: traefik
api:
  dashboard: true
  debug: false
  insecure: false
log:
  level: INFO
accessLog: {}
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      middlewares:
        - compress@file
        - default-security-headers@file
  websecure_tcp:
    address: :444
  traefik:
    address: :8080
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic/
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      # production (default)
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # staging (testing)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: ENC[AES256_GCM,data:Dgfw8a3uiKsDTEoPjp67OzQsOM+LpQ==,iv:OKaLoDTIk9J8gN0AWN5f8VQM+OFsGoA4w5YmvmC9gFk=,tag:jYj8MT/OvSRTqdvpmP+epA==,type:str]
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # disablePropagationCheck: true # Some people using Cloudflare note this can solve DNS propagation issues.
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
sops:
  age:
    - recipient: age10tes8xka8mh6u72vvunf7umwfqv2qquswzwmr6wrcy3yffvut9rqdtthsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZUtpYTRVTDVUb0ZncUxO
        am03anB0emJzYjlJdlcvZXdIUkwxcE0vbm5ZCkRVd2dUVG1rTkdaRk1Xb0QxUnhm
        TkVZS1NvMTkxendyS05UUlRTK1QxQU0KLS0tIFJ6bTNjbjgvZ1FveEo5SVZ4VTh0
        MUFYV21RWkk2amRhT1YwOCtmUko1dHMKuPRE0bsLQcmagPEkE7v4N8bSgdfHwIg4
        n3la5iYSfr6dQsFys9pJUgGxUorpA9BfLyJjqPl167aS4jz6b7hy7Q==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kgzzjlugy0smkex77kvymuwjlhfryh0ljnmqqaw8zx9hh3st0vysha3g97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdVZwcWMxTC9Rd1MzUDhs
        dThMQTkxMW9yNldhY1dtWGp1bUJ2elUyd0JJCmVQLzR0QUhjM1Q2dVhLY1FuMW5R
        ekZ4TExUeWd6anR5UXIwaGN4ejh3VzgKLS0tIDUzenhtTERDSkl0SEVrN3JlVjF2
        UGV5bitkYmhYZ054M2E2QWoraFQzRXMK/dhjJ8fJzQTdzQtg28SCu0JNwHxFssFH
        DejfOYnaUTgj4HXWJla/3DoyRQRvbrpIzWv0EYEYBJLoSf+mCUXzjQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1d4cm2n8gl7ah9s3q73yw6yac26atu8yusl5exy5j8xdpvuza73tqvxsswk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTzlMVmFCUFJEcE51eTFI
        aEdubXFuQ1czN3VUY0ZqR2JBMWZsdFJZVkhBCjVPa3F3TDNnRUdiL1VhTjNZYm05
        V0UvcW1sdTlnb05CdzZRMFY5QU5xVnMKLS0tIE5LK2tPNWsvQzVkbFdybFYrOUpQ
        cmd6bGFGYjlPemZ3cFViQjBSU2NiOUUKq4XrsnScifiXM1BWmX9X9WiAqHkj0zpi
        uKQa2iRz/VkqDT7EPmPCJypQbIO+Z80yTAxh/2OWerc7gACVmeEVeg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T08:36:03Z"
  mac: ENC[AES256_GCM,data:tAr48rOaEgDK+eUJl0qx9YyHOVu8CAXTpIBTmbuA64kvKfY5kKSOqmGW/xmybnLGfKhvaaCa7REBj5ouwMAjhmzEUz6vuwzhGYnUXB2sfhEC0mHKpRRv9NvjXONDJ80v6I3P7OJ0vRKVmyDCW17akt7nCddADP6NtyV3ZBqn3lc=,iv:mBA76f08sRqpzff7q9b3X3GU3qMz159oVCJEHXrviaM=,tag:vvxyRiNMOsmb0qtGUiiyRg==,type:str]
  encrypted_regex: ^(webhookURL|email)$
  version: 3.11.0
