---
general:
  checkNewVersion: false
  sendAnonymousUsage: false
ping:
  entryPoint: traefik
api:
  dashboard: true
  debug: false
  insecure: false
log:
  level: INFO
accessLog: {}
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
  traefik:
    address: :8080
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/config.yml
certificatesResolvers:
  cloudflare:
    acme:
      # caServer: https://acme-v02.api.letsencrypt.org/directory # production (default)
      # staging (testing)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: ENC[AES256_GCM,data:2URXKE3vRN7m2RImDPnqIX2n8c9o7A==,iv:yocUuGlkbmNQHOdkGlyUqVm1Iqq7tlm+K0zxr96KS9g=,tag:TvTZdnSFElS4tWZZHWwh+w==,type:str]
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        # disablePropagationCheck: true # Some people using Cloudflare note this can solve DNS propagation issues.
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
sops:
  age:
    - recipient: age10tes8xka8mh6u72vvunf7umwfqv2qquswzwmr6wrcy3yffvut9rqdtthsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOVRWZXFJdXFtNU4vUnJ3
        YjFHSGhuaDRlQWhiOTJzK29wZzNlZlF1cmhZCmpORWJuNkZWTG9uNXNSdDE4TEpU
        S28yUEJXdGVmUTFZL0tZVnBmYVRaODgKLS0tIEZaV3huRXI3RlRXRXVRMkNoS2c0
        YjZWZ25nejF4MUZVYW82eVE2S1B4L0UK6EXnDiaMdm7/4gGwPwfaI1estpiRXcy3
        JnFQB2tMMnVvv5+YWoof8h083Lvj/7CZiUQCEJmhQTd5Xy6yN5MATw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1kgzzjlugy0smkex77kvymuwjlhfryh0ljnmqqaw8zx9hh3st0vysha3g97
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR3RkU1g3VkdXR08vdDlx
        bnNRK2VMYXZoSkdJU0t4STQ2MjdUUE1sZ3hVClhZdi8raldqYXBtcTZYN0FNWGtS
        QVNyTVpoeTEyUWVwNTBZNFYwNkROUXMKLS0tIFZzd3ZLVlM5Wk40VTdRcG5YdElh
        TGNVZTVsaHpWT0lQK0Z5MGtrcS9RQ2MKvlh4KqDcISSN3jBZdqnXEMr3EuLFzx2e
        angXl+3AfOq0ezGVBURX0udSxcQFwYM0ib+BC72aKo9gICYQEs0pDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T11:49:08Z"
  mac: ENC[AES256_GCM,data:2mi1S1+p2QB9/ftwZv9ciaHCgti/IKOMnaRjLGjFmz15TdVL3YYO3fweVf6KuzXttzU+KJZ6g6qcjFl7gkGFm9pvQMgQomsKElQuo0G0Cxxs5vl5P02icW6Rh2EBTkZjAdK693KTLAT+qXcmDrEyeLfcOUN0V5Jbt2UcyhIug+Y=,iv:Gy3rYDJeWodZKDJl5FNmIiz4vToiOQbi88ODkPoQwBo=,tag:zV0rQnvhTCHTJY34K/Fexg==,type:str]
  encrypted_regex: ^(webhookURL|email)$
  version: 3.11.0
