---
services:
  diun:
    extends:
      file: ../common.yml
      service: common-config
    image: crazymax/diun:latest
    container_name: diun
    environment:
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_NOTIF_DISCORD_WEBHOOKURL}
      - LOG_JSON=${LOG_JSON}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./diun.yml:/diun.yml:ro
      - /opt/diun/data:/data
      - ./images.yml:/data/images.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: [CMD, diun, --version]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: serve
