---
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    networks:
      proxy:
        ipv4_address: 172.19.0.123
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/config:/opt/adguardhome/conf
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.adguard-secure.entrypoints=https"
      - "traefik.http.routers.adguard-secure.rule=Host(`adguard.${DOMAIN}`)"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.routers.adguard-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.adguard-secure.service=adguard"
      - "traefik.http.routers.adguard-secure.middlewares=compress@file"
      - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      - diun.enable=true
    restart: unless-stopped
networks:
  proxy:
    external: true
