---
services:
  backend:
    extends:
      file: ../common.yml
      service: common-config
    container_name: infisical-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    image: infisical/infisical:latest-postgres
    pull_policy: always
    env_file: .env.prod
    ports:
      - "82:8080"
    environment:
      - NODE_ENV=production
    networks:
      - infisical_int
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.infisical-secure.entrypoints=https"
      - "traefik.http.routers.infisical-secure.rule=Host(`infisical.${DOMAIN}`)"
      - "traefik.http.routers.infisical-secure.tls=true"
      - "traefik.http.routers.infisical-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.infisical-secure.service=infisical"
      - "traefik.http.services.infisical.loadbalancer.server.port=8080"
    healthcheck:
      test: "curl -fsS http://localhost:8080/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  redis:
    extends:
      file: ../common.yml
      service: common-config
    image: redis
    container_name: infisical-redis
    env_file: .env.prod
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - infisical_int
    volumes:
      - redis_data:/data
  db:
    extends:
      file: ../common.yml
      service: common-config
    container_name: infisical-db
    image: postgres:14-alpine
    env_file: .env.prod
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical_int
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
networks:
  infisical_int:
    internal: true
  proxy:
    external: true
