---
services:
  backend:
    extends:
      file: ../common.yml
      service: common-config
    image: infisical/infisical:latest-postgres
    container_name: infisical-backend
    environment:
      - NODE_ENV=production
    env_file: .env.prod
    networks:
      - infisical_int
      - proxy
    ports:
      - "82:8080"
    healthcheck:
      test: curl -fsS http://localhost:8080/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.infisical-secure.entrypoints=https
      - traefik.http.routers.infisical-secure.rule=Host(`infisical.${DOMAIN}`)
      - traefik.http.routers.infisical-secure.tls=true
      - traefik.http.routers.infisical-secure.tls.certresolver=cloudflare
      - traefik.http.routers.infisical-secure.service=infisical
      - traefik.http.services.infisical.loadbalancer.server.port=8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    pull_policy: always
  db:
    extends:
      file: ../common.yml
      service: common-config
    image: postgres:18-alpine
    container_name: infisical-db
    env_file: .env.prod
    networks:
      - infisical_int
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username=$$POSTGRES_USER && psql --username=$$POSTGRES_USER --list
      interval: 5s
      timeout: 10s
      retries: 10
  redis:
    extends:
      file: ../common.yml
      service: common-config
    image: redis
    container_name: infisical-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    env_file: .env.prod
    networks:
      - infisical_int
    volumes:
      - redis_data:/data
networks:
  infisical_int:
    internal: true
  proxy:
    external: true
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
