---
services:
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:latest
    container_name: cross-seed
    user: ${PUID}:${PGID}
    env_file:
      - .env
    volumes:
      - /opt/cross-seed/config:/config
      - ${MEDIA}:/media
    networks:
      - proxy
    command: daemon
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2468/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  proxy:
    external: true
