---
services:
  kapowarr:
    container_name: kapowarr
    image: mrcas/kapowarr:latest
    env_file:
      - /secrets/kapowarr.env
    networks:
      proxy:
    volumes:
      - /opt/kapowarr/config:/config
      - ${MEDIA}:/media
      - ${MEDIA}/downloads:/app/temp_downloads
    ports:
      - "5656:5656"
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:5656\")' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.kapowarr-secure.entrypoints=https"
      - "traefik.http.routers.kapowarr-secure.rule=Host(`kapowarr.${DOMAIN}`)"
      - "traefik.http.routers.kapowarr-secure.tls=true"
      - "traefik.http.routers.kapowarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.kapowarr-secure.service=kapowarr"
      - "traefik.http.routers.kapowarr-secure.middlewares=compress@file"
      - "traefik.http.services.kapowarr.loadbalancer.server.port=5656"
networks:
  proxy:
    external: true
