---
services:
  nicotineplus-proper:
    image: sirjmann92/nicotineplus-proper:latest
    container_name: nicotine
    env_file:
      - .env
    network_mode: container:gluetun
    volumes:
      - ${MEDIA}/musics/not_imported:/downloads
      - ${MEDIA}/musics:/musics
      - /opt/nicotine/shared:/shared
      - /opt/nicotine/config:/config
      - /opt/nicotine/config/data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:6565/ >/dev/null 2>&1 && curl -fsS --max-time 5 https://google.com >/dev/null 2>&1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      diun.enable: true
      autoheal: true
