---
services:
  nicotineplus-proper:
    image: 'sirjmann92/nicotineplus-proper:latest'
    container_name: nicotine
    network_mode: container:gluetun
    env_file: .env
    volumes:
      - ${MEDIA}/musics/not_imported:/downloads
      - ${MEDIA}/musics:/musics
      - /opt/nicotine/shared:/shared
      - /opt/nicotine/config:/config
      - /opt/nicotine/config/data:/data
    restart: unless-stopped
