---
services:
  nicotineplus-proper:
    image: 'sirjmann92/nicotineplus-proper:latest'
    container_name: nicotine
    network_mode: container:gluetun
    env_file: .env
    volumes:
      - ${MEDIA}/musics/not_imported:/downloads
      - ${MEDIA}/musics:/musics
      - /opt/nicotine/shared:/shared
      - /opt/nicotine/config:/config
      - /opt/nicotine/config/data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:6565/ && curl -fsS --max-time 5 https://google.com"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      autoheal: true
