---
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dozzle-secure.entrypoints=https"
      - "traefik.http.routers.dozzle-secure.rule=Host(`dozzle.${DOMAIN}`)"
      - "traefik.http.routers.dozzle-secure.tls=true"
      - "traefik.http.routers.dozzle-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.dozzle-secure.service=dozzle"
      - "traefik.http.routers.dozzle-secure.middlewares=compress@file"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
networks:
  proxy:
    external: true
