---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      proxy:
    mem_limit: 512M
    env_file:
      - .env
    volumes:
      - /opt/bazarr/config:/config
      - ${MEDIA}:/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.bazarr-secure.entrypoints=https"
      - "traefik.http.routers.bazarr-secure.rule=Host(`bazarr.${DOMAIN}`)"
      - "traefik.http.routers.bazarr-secure.tls=true"
      - "traefik.http.routers.bazarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.bazarr-secure.service=bazarr"
      - "traefik.http.routers.bazarr-secure.middlewares=compress@file"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
networks:
  proxy:
    external: true
