---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:nightly
    container_name: lidarr
    networks:
      proxy:
    env_file: .env
    volumes:
      - /opt/lidarr/config:/config
      - /opt/lidarr/custom-services.d:/custom-services.d
      - ./custom-cont-init.d:/custom-cont-init.d
      - ${MEDIA}:/media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.lidarr-secure.entrypoints=https"
      - "traefik.http.routers.lidarr-secure.rule=Host(`lidarr.${DOMAIN}`)"
      - "traefik.http.routers.lidarr-secure.tls=true"
      - "traefik.http.routers.lidarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.lidarr-secure.service=lidarr"
      - "traefik.http.routers.lidarr.middlewares=compress@file"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
networks:
  proxy:
    external: true
