---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    env_file:
      - /secrets/uptime-kuma.env
    networks:
      proxy:
    volumes:
      - /opt/uptime-kuma/config:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.uptime-kuma-secure.entrypoints=https"
      - "traefik.http.routers.uptime-kuma-secure.rule=Host(`uptime-kuma.${DOMAIN}`)"
      - "traefik.http.routers.uptime-kuma-secure.tls=true"
      - "traefik.http.routers.uptime-kuma-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.uptime-kuma-secure.service=uptime-kuma"
      - "traefik.http.routers.uptime-kuma-secure.middlewares=compress@file"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
networks:
  proxy:
    external: true
