---
services:
  uptime-kuma:
    extends:
      file: ../common.yml
      service: common-config
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    networks:
      - proxy
    volumes:
      - /opt/uptime-kuma/config:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.uptime-kuma-secure.entrypoints=https
      - traefik.http.routers.uptime-kuma-secure.rule=Host(`uptime-kuma.${DOMAIN}`)
      - traefik.http.routers.uptime-kuma-secure.tls=true
      - traefik.http.routers.uptime-kuma-secure.tls.certresolver=cloudflare
      - traefik.http.routers.uptime-kuma-secure.service=uptime-kuma
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
