---
services:
  weechat:
    image: weechat/weechat:latest-alpine
    platform: linux/arm64
    container_name: weechat
    env_file:
      - .env
    network_mode: container:gluetun
    volumes:
      - /opt/weechat:/home/weechat/.weechat
    tty: true
    stdin_open: true
    restart: unless-stopped
    labels:
      diun.enable: true
      autoheal: true
