---
services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server
    container_name: suwayomi
    network_mode: container:gluetun
    env_file:
      - .env
    volumes:
      - /opt/suwayomi/data:/home/suwayomi/.local/share/Tachidesk
      - ${MEDIA}/books:/home/suwayomi/.local/share/Tachidesk/downloads
    restart: unless-stopped
    labels:
      diun.enable: true
      autoheal: true
