---
services:
  suwayomi:
    extends:
      file: ../common.yml
      service: common-config
    image: ghcr.io/suwayomi/suwayomi-server
    container_name: suwayomi
    networks:
      - proxy
    env_file:
      - .env
    volumes:
      - /opt/suwayomi/data:/home/suwayomi/.local/share/Tachidesk
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.suwayomi-secure.entrypoints=https"
      - "traefik.http.routers.suwayomi-secure.rule=Host(`suwayomi.${DOMAIN}`)"
      - "traefik.http.routers.suwayomi-secure.tls=true"
      - "traefik.http.routers.suwayomi-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.suwayomi-secure.service=suwayomi"
      - "traefik.http.services.suwayomi.loadbalancer.server.port=4567"
networks:
  proxy:
    external: true
