---
services:
  komf:
    extends:
      file: ../common.yml
      service: common-config
    image: sndxr/komf:latest
    container_name: komf
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - /opt/komf/config:/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.komf-secure.entrypoints=https
      - traefik.http.routers.komf-secure.rule=Host(`komf.${DOMAIN}`)
      - traefik.http.routers.komf-secure.tls=true
      - traefik.http.routers.komf-secure.tls.certresolver=cloudflare
      - traefik.http.routers.komf-secure.service=komf
      - traefik.http.services.komf.loadbalancer.server.port=8085
networks:
  proxy:
    external: true
