---
services:
  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: qui
    network_mode: "container:gluetun"
    env_file:
      - .env
    volumes:
      - /opt/qui:/config
      - ${MEDIA}:/media
    restart: unless-stopped
