---
services:
  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: qui
    networks:
      proxy:
    env_file:
      - .env
    volumes:
      - /opt/qui:/config
      - ${MEDIA}:/media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.qui-secure.entrypoints=https"
      - "traefik.http.routers.qui-secure.rule=Host(`qui.${DOMAIN}`)"
      - "traefik.http.routers.qui-secure.tls=true"
      - "traefik.http.routers.qui-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.qui-secure.service=qui"
      - "traefik.http.routers.qui-secure.middlewares=compress@file"
      - "traefik.http.services.qui.loadbalancer.server.port=7476"
networks:
  proxy:
    external: true
