---
services:
  lingarr:
    image: lingarr/lingarr:latest-arm64
    container_name: lingarr
    networks:
      proxy:
    restart: unless-stopped
    env_file: .env
    volumes:
      - /opt/lingarr/config:/config
      - ${MEDIA}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.lingarr-secure.entrypoints=https"
      - "traefik.http.routers.lingarr-secure.rule=Host(`lingarr.${DOMAIN}`)"
      - "traefik.http.routers.lingarr-secure.tls=true"
      - "traefik.http.routers.lingarr-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.lingarr-secure.service=lingarr"
      - "traefik.http.routers.lingarr-secure.middlewares=compress@file"
      - "traefik.http.services.lingarr.loadbalancer.server.port=9876"
networks:
  proxy:
    external: true
