---
services:
  jellyseerr:
    extends:
      file: ../common.yml
      service: common-config
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - /opt/jellyseerr/appdata/config:/app/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jellyseerr-secure.entrypoints=https
      - traefik.http.routers.jellyseerr-secure.rule=Host(`jellyseerr.${DOMAIN}`)
      - traefik.http.routers.jellyseerr-secure.tls=true
      - traefik.http.routers.jellyseerr-secure.tls.certresolver=cloudflare
      - traefik.http.routers.jellyseerr-secure.service=jellyseerr
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
      - traefik.http.routers.jellyseerr-secure.middlewares=authentik-forwardauth@file,no-index@file
    mem_limit: 1024M
networks:
  proxy:
    external: true
